# Importando bibliotecas

In [ ]:
import pandas as pd

# Etapa 1

In [ ]:
#Armazenando as bases de dados em datasets separados
df_entregas_orquideas = pd.read_csv("/content/entregas_orquideas.csv")
df_estufas_qualidade = pd.read_csv("/content/estufas_qualidade.csv")
df_telemetria_iot = pd.read_csv("/content/telemetria_iot.csv")

In [ ]:
#exibição dos 5 primeiros registros da tabela de entregas de orquideas
df_entregas_orquideas.head()

,ID_Carga,Placa_Caminhao,Estufa_Origem,UF_Destino,Qtd_Orquideas,Status_Entrega
0,LOG-1000,TX-103,EST-3,SP,457,Entregue
1,LOG-1001,TX-100,EST-1,SC,165,Entregue
2,LOG-1002,TX-108,EST-2,MG,124,Entregue
3,LOG-1003,TX-107,EST-1,RJ,162,Entregue
4,LOG-1004,TX-107,EST-2,SP,469,Entregue

In [ ]:
#exibição dos 5 primeiros registros da tabela de qualidade de estufas
df_estufas_qualidade.head()

,id_estufa,especie_predominante,umidade_media_pct,responsavel_tecnico,indice_qualidade_lote
0,EST-1,Phalaenopsis,75,Ana Silva,0.95
1,EST-2,Cattleya,82,Carlos Mendes,0.88
2,EST-3,Dendrobium,65,Mariana Costa,0.91

In [ ]:
#exibição dos 5 primeiros registros da tabela de telemetria
df_telemetria_iot.head()

  Placa_Caminhao  Temperatura_C Alerta_Calor status_temperatura
0         TX-103             20          NAO                 OK
1         TX-100             30          SIM             Alerta
2         TX-108             28          SIM             Alerta
3         TX-107             33          SIM             Alerta
4         TX-104             20          NAO                 OK

# Etapa 2

In [ ]:
list_status_temperatura = []

list_temps = df_telemetria_iot['Temperatura_C'].tolist()

for temp in list_temps:
    if temp >= 28:
        list_status_temperatura.append("Alerta")
    else:
        list_status_temperatura.append("OK")

display(list_status_temperatura)

df_telemetria_iot['status_temperatura'] = list_status_temperatura

['OK',
 'Alerta',
 'Alerta',
 'Alerta',
 'OK',
 'OK',
 'Alerta',
 'Alerta',
 'Alerta',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'Alerta']

In [ ]:
#exibição dos 5 primeiros registros
df_telemetria_iot.head()

  Placa_Caminhao  Temperatura_C Alerta_Calor status_temperatura
0         TX-103             20          NAO                 OK
1         TX-100             30          SIM             Alerta
2         TX-108             28          SIM             Alerta
3         TX-107             33          SIM             Alerta
4         TX-104             20          NAO                 OK

# Etapa 3

In [ ]:
#Soma de todas as orquideas entregues
tot_orquideas = df_entregas_orquideas['Qtd_Orquideas'].sum()

print(f"No total foram entregues {tot_orquideas} orquídeas")

No total foram entregues 55425 orquídeas

In [ ]:
#Contagem das orquideas que foram perdidas

orquid_perdidas = df_entregas_orquideas[df_entregas_orquideas['Status_Entrega'] == 'Cancelado']

result_orquid_perdidas = orquid_perdidas['Qtd_Orquideas'].sum()

print(f'No total foram perdidas {result_orquid_perdidas} orquídeas')

No total foram perdidas 6349 orquídeas

In [ ]:
#Estado com as maiores perdas de orquídeas
maximo_orquideas_por_regiao = orquid_perdidas['UF_Destino'].value_counts().idxmax()
maximo_orquideas_por_regiao
print(f'O estado com mais perdas foi {maximo_orquideas_por_regiao}')

O estado com mais perdas foi SP

In [ ]:
#Temperatura máxima e temperatura média registradas nos caminhões
temp_max = df_telemetria_iot['Temperatura_C'].max()
print(f'A temperatura máxima registrada foi de: {temp_max}ºC')

temp_media = df_telemetria_iot['Temperatura_C'].mean()
print(f'A temperatura máxima registrada foi de: {temp_media}ºC')

A temperatura máxima registrada foi de: 34ºC
A temperatura máxima registrada foi de: 27.0ºC